"""make bots.id autoincrement

Revision ID: 20260813_0009
Revises: 20260813_0008
Create Date: 2026-08-13 00:40:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "20260813_0009"
down_revision: Union[str, None] = "20260813_0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        # Recreate table so SQLite writes the AUTOINCREMENT keyword.
        with op.batch_alter_table(
            "bots",
            recreate="always",
            table_kwargs={"sqlite_autoincrement": True},
        ) as batch_op:
            batch_op.alter_column(
                "id",
                existing_type=sa.Integer(),
                nullable=False,
                autoincrement=True,
            )
        return

    if dialect == "postgresql":
        op.execute("ALTER TABLE bots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        op.execute(
            """
            DO $$
            DECLARE seq_name text;
            BEGIN
                SELECT pg_get_serial_sequence('bots', 'id') INTO seq_name;
                IF seq_name IS NOT NULL THEN
                    EXECUTE format(
                        'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM bots), 1), true)',
                        seq_name
                    );
                END IF;
            END $$;
            """
        )
        return

    if dialect == "mysql":
        op.execute("ALTER TABLE bots MODIFY COLUMN id INTEGER NOT NULL AUTO_INCREMENT")
        return

    op.alter_column(
        "bots",
        "id",
        existing_type=sa.Integer(),
        nullable=False,
        autoincrement=True,
    )


def downgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        # Recreate table without explicit AUTOINCREMENT.
        with op.batch_alter_table(
            "bots",
            recreate="always",
        ) as batch_op:
            batch_op.alter_column(
                "id",
                existing_type=sa.Integer(),
                nullable=False,
                autoincrement=False,
            )
        return

    if dialect == "postgresql":
        op.execute("ALTER TABLE bots ALTER COLUMN id DROP IDENTITY IF EXISTS")
        return

    if dialect == "mysql":
        op.execute("ALTER TABLE bots MODIFY COLUMN id INTEGER NOT NULL")
        return

    op.alter_column(
        "bots",
        "id",
        existing_type=sa.Integer(),
        nullable=False,
        autoincrement=False,
    )
